<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli') exit;
require dirname(__DIR__).'/app/core.php';
require dirname(__DIR__).'/vendor/autoload.php';
if(config()['environment']!=='local') exit("Tests require a local configuration.\n");
$_SESSION=['csrf'=>'test-token'];
$testDb='assembly_test_'.bin2hex(random_bytes(6));
$checks=0;
function check(bool $ok,string $label): void { global $checks; if(!$ok) throw new RuntimeException('FAIL: '.$label); $checks++; echo "PASS $label\n"; }
function rejects(callable $fn,string $label): void { try { $fn(); } catch(DomainException $e) { check(true,$label); return; } throw new RuntimeException('FAIL: '.$label.' (not rejected)'); }
try {
    db()->exec("CREATE DATABASE `$testDb` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
    db()->exec("USE `$testDb`");
    db()->exec(file_get_contents(dirname(__DIR__).'/app/schema.sql'));
    db()->exec("SET SESSION sql_mode = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,ONLY_FULL_GROUP_BY'");
    check(election()['phase']==='draft','Fresh election starts in draft');
    rejects(fn()=>changePhase('nomination'),'Cannot open an empty election');
    rejects(fn()=>changePhase('voting'),'Cannot skip election phases');
    $members=[];
    foreach(['Ana','Ben','Cara','Dion'] as $i=>$n) $members[]=['first_name'=>$n,'last_name'=>'Test','middle_initial'=>'A','email'=>strtolower($n).'@example.test'];
    [$added,$skipped]=addMembers($members); check($added===4 && $skipped===0,'Add four eligible members');
    [$added,$skipped]=addMembers([$members[0]]); check($added===0 && $skipped===1,'Duplicate email is skipped');
    rejects(fn()=>addMembers([['first_name'=>'X','last_name'=>'X','email'=>'bad']]),'Invalid email is rejected');
    $mixed=[$members[0],['first_name'=>'New','last_name'=>'Member','email'=>'new@example.test'],['email'=>'bad']];
    rejects(fn()=>addMembers($mixed),'Invalid import rolls back');
    check((int)query('SELECT COUNT(*) FROM members')->fetchColumn()===4,'Import is atomic');
    $csv=tempnam(dirname(__DIR__).'/storage','csv');
    file_put_contents($csv,"\xEF\xBB\xBFfirst_name,last_name,middle_initial,email\n\"Mia, Rose\",Santos,J,mia@example.test\n");
    $parsed=parseCsv($csv); check($parsed[0]['first_name']==='Mia, Rose','CSV handles BOM and quoted commas');
    file_put_contents($csv,"first_name,last_name,email\nA,B,a@example.test\n"); rejects(fn()=>parseCsv($csv),'CSV requires template headers'); unlink($csv);
    query('UPDATE elections SET nomination_limit=2,vote_limit=1,officer_count=1 WHERE id=1');
    $ids=array_map('intval',query('SELECT id FROM members ORDER BY id')->fetchAll(PDO::FETCH_COLUMN));
    [$a,$b,$c,$d]=$ids;
    changePhase('nomination');
    rejects(fn()=>submitBallot($a,'nomination',1,[]),'Empty ballot is rejected');
    rejects(fn()=>submitBallot($a,'nomination',1,[$a,$b,$c]),'Selection limit is enforced on server');
    rejects(fn()=>submitBallot($a,'nomination',1,[$a,$a]),'Repeated selections are rejected');
    rejects(fn()=>submitBallot($a,'nomination',1,[$a,99999]),'Unknown nominee is rejected');
    rejects(fn()=>submitBallot(99999,'nomination',1,[$a]),'Unregistered voter is rejected');
    rejects(fn()=>submitBallot($a,'nomination',99,[$a]),'Stale election generation is rejected');
    check((int)query('SELECT COUNT(*) FROM submissions')->fetchColumn()===0,'Rejected ballots leave no submissions');
    submitBallot($a,'nomination',1,[$b,$c]);
    rejects(fn()=>submitBallot($a,'nomination',1,[$d]),'Second nomination ballot is rejected');
    submitBallot($b,'nomination',1,[$b,$d]);
    $t=tally('nomination'); check((int)$t[0]['id']===$b && (int)$t[0]['votes']===2,'Repeated nominations tally correctly');
    rejects(fn()=>decideNominee($b,'accepted'),'Responses cannot change while nominations are open');
    changePhase('review');
    rejects(fn()=>submitBallot($c,'nomination',1,[$b]),'Closed nominations reject ballots');
    rejects(fn()=>addMembers([['first_name'=>'New','last_name'=>'Member','email'=>'new@example.test']]),'Member register locks after nominations');
    rejects(fn()=>changePhase('voting'),'Pending responses block voting');
    decideNominee($b,'accepted'); decideNominee($c,'accepted'); decideNominee($d,'denied');
    rejects(fn()=>decideNominee($a,'accepted'),'Non-nominees cannot be accepted');
    changePhase('voting');
    check(count(tally('voting'))===2,'Voting contains accepted candidates only');
    rejects(fn()=>decideNominee($d,'accepted'),'Decisions freeze when voting opens');
    rejects(fn()=>submitBallot($a,'voting',1,[$d]),'Denied nominee cannot receive votes');
    submitBallot($a,'voting',1,[$b]);
    rejects(fn()=>submitBallot($a,'voting',1,[$c]),'Second voting ballot is rejected');
    submitBallot($b,'voting',1,[$c]);
    $rank=rankResults(tally('voting'),1);
    check($rank[0]['result']==='Tied — review required' && $rank[1]['result']==='Tied — review required','Boundary tie does not arbitrarily elect a winner');
    submitBallot($c,'voting',1,[$b]);
    changePhase('closed');
    rejects(fn()=>submitBallot($d,'voting',1,[$b]),'Closed voting rejects ballots');
    $rank=rankResults(tally('voting'),1);
    check($rank[0]['result']==='Elected' && (int)$rank[0]['votes']===2 && $rank[1]['result']==='Not elected','Top result selects configured number of officers');
    check(rankResults([['votes'=>0],['votes'=>0]],2)[0]['result']==='No votes','Zero-vote candidates are not elected');
    $makeOtp=function(string $purpose='voting',int $expires=600) {
        $id=bin2hex(random_bytes(16)); query('INSERT INTO otp_challenges (id,email,purpose,code_hash,context_hash,expires_at) VALUES (?,?,?,?,?,?)',[$id,'ana@example.test',$purpose,password_hash('123456',PASSWORD_DEFAULT),hash('sha256','session'),gmdate('Y-m-d H:i:s',time()+$expires)]); return $id;
    };
    $otp=$makeOtp();
    rejects(fn()=>consumeOtp($otp,'ana@example.test','nomination','session','123456'),'OTP is stage-bound');
    rejects(fn()=>consumeOtp($otp,'ana@example.test','voting','other-session','123456'),'OTP is session-bound');
    rejects(fn()=>consumeOtp($otp,'ben@example.test','voting','session','123456'),'OTP is email-bound');
    consumeOtp($otp,'ana@example.test','voting','session','123456');
    rejects(fn()=>consumeOtp($otp,'ana@example.test','voting','session','123456'),'Used OTP cannot be replayed');
    $otp=$makeOtp('voting',-1); rejects(fn()=>consumeOtp($otp,'ana@example.test','voting','session','123456'),'Expired OTP is rejected');
    $otp=$makeOtp(); for($i=0;$i<5;$i++) rejects(fn()=>consumeOtp($otp,'ana@example.test','voting','session','000000'),'Wrong OTP attempt '.($i+1));
    rejects(fn()=>consumeOtp($otp,'ana@example.test','voting','session','123456'),'OTP locks after five failures');
    rateLimit('test',2,60); rateLimit('test',2,60); rejects(fn()=>rateLimit('test',2,60),'Rate limit blocks excess attempts');
    $_POST=['csrf'=>'wrong']; rejects(fn()=>checkCsrf(),'Invalid CSRF is rejected'); $_POST=['csrf'=>'test-token']; checkCsrf(); check(true,'Valid CSRF is accepted');
    resetElection('votes',1);
    check(election()['phase']==='review' && (int)election()['generation']===2,'Vote reset returns to review and increments generation');
    check((int)query("SELECT COUNT(*) FROM submissions WHERE stage='voting'")->fetchColumn()===0 && count(tally('nomination'))===3,'Vote reset preserves nominations');
    changePhase('voting'); rejects(fn()=>submitBallot($a,'voting',1,[$b]),'Reset invalidates earlier verification');
    submitBallot($a,'voting',2,[$b]);
    resetElection('election',2);
    db()->exec("SET SESSION sql_mode = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,ONLY_FULL_GROUP_BY'");
    check(election()['phase']==='draft' && (int)query('SELECT COUNT(*) FROM members')->fetchColumn()===4 && count(tally('nomination'))===0,'Election reset retains members and clears ballots');
    rejects(fn()=>resetElection('all',2),'Stale reset request is rejected');
    resetElection('all',3);
    check((int)query('SELECT COUNT(*) FROM members')->fetchColumn()===0,'Full reset clears member register');
    check((int)query('SELECT COUNT(*) FROM audit_log')->fetchColumn()>0,'Reset retains audit history');
    $qr=Endroid\QrCode\QrCode::create('https://example.test/index.php?page=participate&stage=voting');
    $svg=(new Endroid\QrCode\Writer\SvgWriter())->write($qr)->getString();
    check(str_contains($svg,'<svg') && strlen($svg)>1000,'QR code generates a real SVG');
    require dirname(__DIR__).'/app/views.php';
    foreach(['dashboard','membersPage','nominationsPage','votingPage','resultsPage','settingsPage'] as $view) { ob_start(); $view(election()); $html=ob_get_clean(); check(strlen($html)>100,'View renders: '.$view); }
    echo "\n$checks checks passed.\n";
} finally {
    if(db()->inTransaction()) db()->rollBack();
    if(preg_match('/^assembly_test_[a-f0-9]{12}$/',$testDb)) db()->exec("DROP DATABASE IF EXISTS `$testDb`");
}
