<?php
function icon(string $name, string $class=''): string {
    $paths=[
        'grid'=>'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
        'users'=>'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m20 0v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/><circle cx="9" cy="7" r="4"/>',
        'check'=>'<path d="m5 12 4 4L19 6"/>',
        'ballot'=>'<path d="m9 9 3 3 7-7M4 10v10h16V10M3 15h18M7 4h8"/>',
        'chart'=>'<path d="M4 3v18h17M9 16v-5m5 5V7m5 9V4"/>',
        'settings'=>'<path d="M4 7h16M4 17h16"/><circle cx="8" cy="7" r="3"/><circle cx="16" cy="17" r="3"/>',
        'clock'=>'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
        'arrow'=>'<path d="M5 12h14m-5-5 5 5-5 5"/>',
        'plus'=>'<path d="M12 5v14M5 12h14"/>',
        'download'=>'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',
        'shield'=>'<path d="m12 3 8 4v5c0 5-8 9-8 9s-8-4-8-9V7l8-4Z"/><path d="m8 12 3 3 5-6"/>',
        'mail'=>'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',
        'logout'=>'<path d="M9 4H4v16h5m6-13 5 5-5 5m-7-5h12"/>',
        'search'=>'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',
        'trophy'=>'<path d="M8 3h8v7a4 4 0 0 1-8 0V3Zm0 2H4v3a4 4 0 0 0 4 4m8-7h4v3a4 4 0 0 1-4 4m-4 2v6m-5 1h10"/>',
    ];
    return '<svg class="icon '.e($class).'" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'.($paths[$name]??$paths['grid']).'</svg>';
}
function head(string $title): void { ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#123e36"><title><?=e($title)?> · Assembly</title><link rel="stylesheet" href="assets/bootstrap.min.css"><link rel="stylesheet" href="assets/app.css"><script src="assets/bootstrap.bundle.min.js" defer></script><script src="assets/app.js" defer></script></head><body>
<?php }
function notices(): void { if(isset($_SESSION['flash'])) { [$msg,$type]=$_SESSION['flash']; unset($_SESSION['flash']); ?><div class="alert alert-<?=e($type)?>" role="status"><?=e($msg)?></div><?php } }
function foot(): void { echo '</body></html>'; }
function badge(string $phase): string { return '<span class="status status-'.e($phase).'"><span class="status-dot"></span>'.e(ucfirst($phase)).'</span>'; }
function emptyState(string $title,string $text,string $symbol='users'): void { ?><div class="empty-state"><?=icon($symbol)?><h3><?=e($title)?></h3><p><?=e($text)?></p></div><?php }
function postButton(string $action,string $label,array $hidden=[],string $class='btn-primary',string $confirm=''): void { ?><form method="post" class="d-inline"><?=csrf()?><input type="hidden" name="action" value="<?=e($action)?>"><?php foreach($hidden as $k=>$v):?><input type="hidden" name="<?=e($k)?>" value="<?=e($v)?>"><?php endforeach?><button class="btn <?=e($class)?>" <?= $confirm?'data-confirm="'.e($confirm).'"':''?>><?=e($label)?></button></form><?php }
function stepper(string $phase): void {
    $phases=['draft'=>'Setup','nomination'=>'Nominations','review'=>'Nominee review','voting'=>'Voting','closed'=>'Results']; $current=array_search($phase,array_keys($phases),true); ?>
<div class="election-steps" aria-label="Election progress"><?php $i=0; foreach($phases as $key=>$label): ?><div class="election-step <?=$i<$current?'done':($i===$current?'current':'')?>"><span class="step-number"><?=$i<$current?icon('check'):($i+1)?></span><span><?=e($label)?></span></div><?php $i++; endforeach?></div>
<?php }
function phaseControl(array $el): void {
    $next=['draft'=>['nomination','Open nominations','Members can start submitting nominations. Election limits will be locked.'], 'nomination'=>['review','Close nominations','Stop accepting nominations and begin recording nominee responses.'], 'review'=>['voting','Open voting','Lock nominee decisions and allow members to vote for accepted nominees.'], 'voting'=>['closed','Close voting','Stop accepting ballots and finalize the results.']];
    if(isset($next[$el['phase']])) { [$phase,$label,$confirm]=$next[$el['phase']]; postButton('phase',$label,['next'=>$phase],'btn-primary',$confirm); }
}
function renderAdmin(string $page): void {
    $a=admin(); $el=election(); $nav=['dashboard'=>['grid','Overview'],'members'=>['users','Members'],'nominations'=>['ballot','Nominations'],'voting'=>['check','Voting'],'results'=>['chart','Results'],'settings'=>['settings','Election settings'],'audit'=>['clock','Activity log']];
    head($nav[$page][1]??'Not found'); ?>
<div class="app-shell"><aside class="sidebar"><a class="brand" href="index.php"><span class="brand-mark"><?=icon('ballot')?></span>assembly<span class="brand-period">.</span></a><div class="workspace-label">ELECTION WORKSPACE</div><nav aria-label="Main navigation"><?php foreach($nav as $key=>[$symbol,$label]):?><a class="nav-item <?=$page===$key?'active':''?>" href="index.php?page=<?=e($key)?>" <?=$page===$key?'aria-current="page"':''?>><?=icon($symbol)?><span><?=e($label)?></span><?php if($key===$page):?><span class="nav-dot"></span><?php endif?></a><?php endforeach?></nav><div class="sidebar-note"><?=icon('shield')?><div><strong>Every voice counts.</strong><p>Verified members.<br>One submission per stage.</p></div></div><div class="admin-profile"><span class="avatar"><?=e(mb_substr($a['name'],0,1))?></span><div><strong><?=e($a['name'])?></strong><small>Election administrator</small></div><form method="post"><?=csrf()?><input type="hidden" name="action" value="logout"><button class="icon-button" aria-label="Sign out"><?=icon('logout')?></button></form></div></aside>
<div class="main-shell"><header class="topbar"><div class="breadcrumb-label">Workspace <span>/</span> <strong><?=e($nav[$page][1]??'Not found')?></strong></div><div class="topbar-right"><?=badge($el['phase'])?><span class="date-label"><?=e((new DateTime('now',new DateTimeZone('Asia/Manila')))->format('M d, Y'))?></span></div></header><main class="main-content">
<?php notices(); if(config()['mail']['transport']==='log'):?><div class="local-notice"><?=icon('mail')?> Local preview: verification emails are saved to the private mail log. Connect SMTP before inviting members.</div><?php endif;
    match($page) {
        'dashboard'=>dashboard($el), 'members'=>membersPage($el), 'nominations'=>nominationsPage($el),
        'voting'=>votingPage($el), 'results'=>resultsPage($el), 'settings'=>settingsPage($el), 'audit'=>auditPage(),
        default=>emptyState('Page not found','Choose a page from the navigation.'),
    };
?></main><footer class="app-footer"><span>Assembly · Member elections, made simple</span><span><?=icon('shield')?> Verified participation</span></footer></div></div>
<?php foot(); }
function pageTitle(string $eyebrow,string $title,string $description): void { ?><div class="page-heading"><div><div class="eyebrow"><?=e($eyebrow)?></div><h1><?=e($title)?></h1><p><?=e($description)?></p></div></div><?php }
function dashboard(array $el): void {
    $total=(int)query('SELECT COUNT(*) FROM members WHERE active=1')->fetchColumn();
    $nom=(int)query("SELECT COUNT(*) FROM submissions WHERE stage='nomination'")->fetchColumn();
    $votes=(int)query("SELECT COUNT(*) FROM submissions WHERE stage='voting'")->fetchColumn();
    $accepted=(int)query("SELECT COUNT(*) FROM nominee_decisions WHERE decision='accepted'")->fetchColumn();
    pageTitle('YOUR ELECTION AT A GLANCE','Election overview','Manage your members, nominations, and voting from one place.'); ?>
<section class="election-banner"><div><div class="banner-eyebrow">CURRENT ELECTION <span>•</span> ROUND <?=e($el['generation'])?></div><h2><?=e($el['title'])?></h2><p><?=e(match($el['phase']){'draft'=>'Start with your member register, then open nominations.','nomination'=>'Nominations are open. Your members can now make their voices heard.','review'=>'Record each nominee’s response before opening the ballot.','voting'=>'Voting is open. Every verified member can submit one ballot.','closed'=>'Voting is complete. Your election results are ready.'})?></p><div class="banner-meta"><span><?=icon('users')?> <?=e($el['officer_count'])?> officer positions</span><span><?=icon('ballot')?> Up to <?=e($el['vote_limit'])?> votes per member</span></div></div><div class="banner-action"><?php phaseControl($el); if($el['phase']==='closed'):?><a class="btn btn-light" href="index.php?page=results">View final results <?=icon('arrow')?></a><?php endif?></div></section>
<?php stepper($el['phase']); ?>
<div class="stats-grid"><?php foreach([['Registered members',$total,'Eligible to nominate and vote','users'],['Nomination ballots',$nom,'One submission per member','ballot'],['Accepted nominees',$accepted,'Ready for the voting ballot','check'],['Votes submitted',$votes,($total?round($votes/$total*100):0).'% member turnout','chart']] as [$label,$value,$sub,$symbol]):?><div class="stat-card"><div class="stat-label"><?=e($label)?><?=icon($symbol)?></div><strong><?=e($value)?></strong><small><?=e($sub)?></small></div><?php endforeach?></div>
<div class="row g-4"><div class="col-xl-8"><section class="panel h-100"><div class="panel-heading"><div><h2>Nomination snapshot</h2><p>Members with the most nominations</p></div><a class="text-link" href="index.php?page=nominations">View all <?=icon('arrow')?></a></div><?php $rows=array_slice(tally('nomination'),0,5); if(!$rows) emptyState('Your next leaders start here','Add your members and open nominations to see the tally.','ballot'); else { ?><div class="table-responsive"><table class="table app-table"><thead><tr><th>Member</th><th>Nominations</th><th>Response</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><div class="member-cell"><span class="avatar avatar-soft"><?=e(mb_substr($r['first_name'],0,1).mb_substr($r['last_name'],0,1))?></span><strong><?=e(name($r))?></strong></div></td><td><strong><?=e($r['votes'])?></strong></td><td><?=badge($r['decision'])?></td></tr><?php endforeach?></tbody></table></div><?php }?></section></div><div class="col-xl-4"><section class="panel participation-panel"><div class="panel-heading"><div><h2>Invite your members</h2><p>Share the link or display a QR code.</p></div></div><div class="invite-illustration"><?=icon('users')?><span>→</span><?=icon('mail')?><span>→</span><?=icon('ballot')?></div><p class="body-muted">Members verify their registered email before making their selections.</p><a class="btn btn-outline-primary w-100" href="index.php?page=<?=in_array($el['phase'],['voting','closed'],true)?'voting':'nominations'?>#invite">Get participation QR code <?=icon('arrow')?></a><div class="small-note"><?=icon('shield')?> Only registered members can participate</div></section></div></div>
<?php }
function membersPage(array $el): void {
    pageTitle('MEMBER REGISTER','Your community, ready to participate','Add members individually or import your existing member list.');
    $locked=!in_array($el['phase'],['draft','nomination'],true);
    if(!$locked):?><div class="row g-4 mb-4"><div class="col-xl-7"><section class="panel p-4"><h2>Add a member</h2><form method="post" class="row g-3 mt-1"><?=csrf()?><input type="hidden" name="action" value="add_member"><div class="col-sm-5"><label class="form-label" for="first-name">First name</label><input class="form-control" id="first-name" name="first_name" maxlength="100" required></div><div class="col-sm-5"><label class="form-label" for="last-name">Last name</label><input class="form-control" id="last-name" name="last_name" maxlength="100" required></div><div class="col-sm-2"><label class="form-label" for="initial">Initial</label><input class="form-control" id="initial" name="middle_initial" maxlength="10"></div><div class="col-sm-8"><label class="form-label" for="member-email">Email address</label><input class="form-control" id="member-email" name="email" type="email" maxlength="254" required></div><div class="col-sm-4 d-flex align-items-end"><button class="btn btn-primary w-100"><?=icon('plus')?> Add member</button></div></form></section></div><div class="col-xl-5"><section class="panel p-4 h-100"><h2>Import a CSV</h2><p class="body-muted">Up to 5,000 members per file · Maximum 2 MB</p><form method="post" enctype="multipart/form-data"><?=csrf()?><input type="hidden" name="action" value="import_csv"><label for="csv" class="visually-hidden">Member CSV file</label><input class="form-control mb-3" type="file" name="csv" id="csv" accept=".csv" required><div class="d-flex gap-3 align-items-center flex-wrap"><button class="btn btn-outline-primary">Import members</button><a class="text-link" href="index.php?page=template"><?=icon('download')?> CSV template</a></div></form></section></div></div><?php else:?><div class="alert alert-info">The member register is locked for this election. Reset the election to add more members.</div><?php endif;
    $search=trim((string)($_GET['q']??'')); $p=max(1,(int)($_GET['p']??1)); $where=$search!==''?' WHERE CONCAT(first_name,\' \',last_name,\' \',email) LIKE ?':''; $args=$search!==''?['%'.$search.'%']:[];
    $count=(int)query('SELECT COUNT(*) FROM members'.$where,$args)->fetchColumn(); $pages=max(1,(int)ceil($count/30)); $p=min($p,$pages); $offset=($p-1)*30;
    $rows=query('SELECT * FROM members'.$where.' ORDER BY last_name,first_name,id LIMIT 30 OFFSET '.$offset,$args)->fetchAll(); ?>
<section class="panel"><div class="panel-heading"><div><h2>Member directory <span class="count-pill"><?=e($count)?></span></h2><p>Each unique email represents one member.</p></div><form class="search-field" method="get"><input type="hidden" name="page" value="members"><?=icon('search')?><label class="visually-hidden" for="member-search">Search members</label><input id="member-search" name="q" value="<?=e($search)?>" placeholder="Search name or email"><button class="btn btn-sm btn-light">Search</button></form></div><?php if(!$rows): emptyState('No members found',$search?'Try another name or email.':'Add your first member or upload a CSV to get started.'); else:?><div class="table-responsive"><table class="table app-table"><thead><tr><th>Member name</th><th>Email address</th><th>Membership</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><div class="member-cell"><span class="avatar avatar-soft"><?=e(mb_substr($r['first_name'],0,1).mb_substr($r['last_name'],0,1))?></span><strong><?=e(name($r))?></strong></div></td><td><?=e($r['email'])?></td><td><?=badge('active')?></td></tr><?php endforeach?></tbody></table></div><div class="table-footer"><span>Page <?=e($p)?> of <?=e($pages)?> · <?=e($count)?> members</span><div><?php if($p>1):?><a class="btn btn-sm btn-light" href="index.php?page=members&q=<?=rawurlencode($search)?>&p=<?=$p-1?>">Previous</a><?php endif?> <?php if($p<$pages):?><a class="btn btn-sm btn-light" href="index.php?page=members&q=<?=rawurlencode($search)?>&p=<?=$p+1?>">Next</a><?php endif?></div></div><?php endif?></section>
<?php }
function invitePanel(string $stage): void { $link=url('index.php?page=participate&stage='.$stage); ?>
<section class="panel qr-panel" id="invite"><div><div class="eyebrow">MEMBER ACCESS</div><h2><?= $stage==='nomination'?'Nomination':'Voting'?> QR code</h2><p>Scan, verify your registered email, and make your selections.</p><div class="share-link"><input aria-label="Participation link" readonly value="<?=e($link)?>" id="share-url"><button class="btn btn-outline-primary" data-copy="share-url" type="button">Copy link</button></div><div class="d-flex gap-3 flex-wrap mt-3"><a class="text-link" href="<?=e($link)?>" target="_blank" rel="noopener">Open member page <?=icon('arrow')?></a><a class="text-link" href="index.php?page=qr&stage=<?=e($stage)?>&download=1"><?=icon('download')?> Download QR</a></div><?php if(config()['environment']==='local'):?><p class="small-note mt-3">For phone scanning, set the public HTTPS address in your hosting configuration.</p><?php endif?></div><img src="index.php?page=qr&stage=<?=e($stage)?>" width="180" height="180" alt="QR code for member <?=e($stage)?> page"></section>
<?php }
function nominationsPage(array $el): void {
    pageTitle('FIND YOUR NEXT LEADERS','Nominations','Review the tally and record whether each nominee accepts or declines.'); ?>
<div class="phase-toolbar"><div><?=badge($el['phase'])?> <span>Up to <strong><?=e($el['nomination_limit'])?> nominees</strong> per member</span></div><?php if(in_array($el['phase'],['draft','nomination','review'],true)) phaseControl($el);?></div>
<?php invitePanel('nomination'); $rows=tally('nomination'); ?>
<section class="panel mt-4"><div class="panel-heading"><div><h2>Nomination tally <span class="count-pill"><?=count($rows)?></span></h2><p>Repeated nominations count toward each member’s total.</p></div><a class="btn btn-outline-primary btn-sm" href="index.php?page=export&stage=nomination"><?=icon('download')?> Export CSV</a></div><?php if($el['phase']==='review'):?><div class="inline-info">Confirm each member’s willingness to serve, then mark Accepted or Denied. Resolve every pending response to open voting.</div><?php endif?><?php if(!$rows): emptyState('No nominations yet','The tally will appear here as members submit their nominations.','ballot'); else:?><div class="table-responsive"><table class="table app-table"><thead><tr><th>Nominee</th><th>No. of nominations</th><th>Response</th><th>Action</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><strong><?=e(name($r))?></strong></td><td><span class="vote-count"><?=e($r['votes'])?></span></td><td><?=badge($r['decision'])?></td><td><?php if($el['phase']==='review'):?><form method="post" class="d-flex gap-2"><?=csrf()?><input type="hidden" name="action" value="decision"><input type="hidden" name="member_id" value="<?=e($r['id'])?>"><select class="form-select form-select-sm decision-select" name="decision" aria-label="Response for <?=e(name($r))?>"><?php foreach(['pending'=>'Pending','accepted'=>'Accepted','denied'=>'Denied'] as $k=>$label):?><option value="<?=$k?>" <?=$r['decision']===$k?'selected':''?>><?=$label?></option><?php endforeach?></select><button class="btn btn-sm btn-outline-primary">Save</button></form><?php else:?><span class="text-secondary"><?=$el['phase']==='nomination'?'Available after close':'Locked'?></span><?php endif?></td></tr><?php endforeach?></tbody></table></div><?php endif?></section>
<?php }
function votingPage(array $el): void {
    pageTitle('ONE MEMBER. ONE BALLOT.','Voting','Only nominees who accepted their nomination appear on the ballot.'); ?>
<div class="phase-toolbar"><div><?=badge($el['phase'])?> <span>Choose up to <strong><?=e($el['vote_limit'])?> candidates</strong> · <strong><?=e($el['officer_count'])?> officer positions</strong></span></div><?php if(in_array($el['phase'],['review','voting'],true)) phaseControl($el);?></div>
<?php invitePanel('voting'); $rows=tally('voting'); ?>
<section class="panel mt-4"><div class="panel-heading"><div><h2>Accepted candidates <span class="count-pill"><?=count($rows)?></span></h2><p>The members eligible to receive votes.</p></div><a href="index.php?page=results" class="text-link">View results <?=icon('arrow')?></a></div><?php if(!$rows): emptyState('Your ballot is taking shape','Accepted nominees will appear here after nomination review.','check'); else:?><div class="table-responsive"><table class="table app-table"><thead><tr><th>Candidate</th><th>Ballot status</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><div class="member-cell"><span class="avatar avatar-soft"><?=e(mb_substr($r['first_name'],0,1))?></span><strong><?=e(name($r))?></strong></div></td><td><?=badge('accepted')?></td></tr><?php endforeach?></tbody></table></div><?php endif?></section>
<?php }
function resultsPage(array $el): void {
    $rows=rankResults(tally('voting'),(int)$el['officer_count']); $ballots=(int)query("SELECT COUNT(*) FROM submissions WHERE stage='voting'")->fetchColumn(); $final=$el['phase']==='closed';
    pageTitle($final?'THE COMMUNITY HAS SPOKEN':'ELECTION TALLY',$final?'Final results':'Voting results',$final?'The highest vote totals determine the elected officers.':'Results remain provisional until the administrator closes voting.'); ?>
<div class="result-summary"><div class="result-symbol"><?=icon('trophy')?></div><div><strong><?=e($el['officer_count'])?> officer positions</strong><p><?=e($ballots)?> ballots submitted · <?=$final?'Final tally':'Provisional tally'?></p></div><a class="btn btn-outline-primary ms-auto" href="index.php?page=export&stage=voting"><?=icon('download')?> Export results</a></div>
<?php if(array_filter($rows,fn($r)=>$r['result']==='Tied — review required')):?><div class="alert alert-warning">There is a tie at the final officer position. No tied candidate is automatically declared elected. The administrator must resolve it under the organization’s election rules.</div><?php endif?>
<section class="panel"><div class="panel-heading"><div><h2>Candidate rankings</h2><p>Ranked by total votes. Members with zero votes are not declared elected.</p></div><?=badge($final?'closed':'pending')?></div><?php if(!$rows): emptyState('Results will appear here','Accepted nominees and their vote counts will be listed when the ballot is ready.','chart'); else:?><div class="table-responsive"><table class="table app-table results-table"><thead><tr><th>Rank</th><th>Candidate</th><th>No. of votes</th><th><?=$final?'Result':'Standing'?></th></tr></thead><tbody><?php $max=max(1,(int)$rows[0]['votes']); foreach($rows as $r):?><tr class="<?=$final&&$r['result']==='Elected'?'winner-row':''?>"><td><span class="rank-number"><?=e($r['rank'])?></span></td><td><strong><?=e(name($r))?></strong></td><td><div class="vote-bar-cell"><strong><?=e($r['votes'])?></strong><progress max="<?=$max?>" value="<?=e($r['votes'])?>" aria-label="<?=e($r['votes'])?> votes"></progress></div></td><td><?php $label=$final?$r['result']:($r['result']==='Elected'?'Leading':($r['result']==='Not elected'?'Following':$r['result']));?><span class="result-label <?=$r['result']==='Elected'?'leading':''?>"><?= $r['result']==='Elected'?icon('check'):''?><?=e($label)?></span></td></tr><?php endforeach?></tbody></table></div><?php endif?></section>
<?php }
function settingsPage(array $el): void {
    pageTitle('ELECTION CONTROLS','Election settings','Set participation limits and manage your election lifecycle.'); $locked=$el['phase']!=='draft'; ?>
<div class="row g-4"><div class="col-xl-8"><section class="panel p-4"><h2>Election details</h2><p class="body-muted"><?=$locked?'Settings are locked while this election is in progress.':'Set these limits before opening nominations.'?></p><form method="post"><?=csrf()?><input type="hidden" name="action" value="settings"><fieldset <?=$locked?'disabled':''?>><label for="title" class="form-label">Election title</label><input class="form-control mb-4" name="title" id="title" maxlength="160" value="<?=e($el['title'])?>" required><div class="row g-3"><?php foreach(['nomination_limit'=>['Nominees per member','Maximum names on each nomination.'],'vote_limit'=>['Votes per member','Maximum selections on each ballot.'],'officer_count'=>['Officer positions','Number of top candidates to elect.']] as $k=>[$label,$help]):?><div class="col-md-4"><label class="form-label" for="<?=e($k)?>"><?=e($label)?></label><input class="form-control" type="number" min="1" max="100" id="<?=e($k)?>" name="<?=e($k)?>" value="<?=e($el[$k])?>" required><div class="form-text"><?=e($help)?></div></div><?php endforeach?></div><button class="btn btn-primary mt-4">Save settings</button></fieldset></form></section><section class="panel p-4 mt-4"><h2>Election phase</h2><?php stepper($el['phase']); phaseControl($el);?></section></div><div class="col-xl-4"><section class="panel p-4"><div class="eyebrow">EMAIL VERIFICATION</div><h2>Delivery settings</h2><p class="body-muted">Members receive a six-digit code that expires in 10 minutes.</p><dl class="settings-list"><dt>Delivery method</dt><dd><?=config()['mail']['transport']==='smtp'?'SMTP':'Local mail log'?></dd><dt>Sender</dt><dd><?=e(config()['mail']['from_email'])?></dd><dt>Code attempts</dt><dd>5 per code</dd><dt>Resend cooldown</dt><dd>60 seconds</dd></dl><p class="small-note">Your hosting configuration controls the email connection.</p></section></div></div>
<section class="panel danger-panel mt-4"><div class="panel-heading"><div><h2>Reset election data</h2><p>Requires your admin password, an email code, and typed confirmation.</p></div><?=icon('shield')?></div><div class="p-4 pt-0"><?php $r=$_SESSION['reset']??null; if($r):?><div class="alert alert-warning">Pending reset: <strong><?=e(['votes'=>'Voting ballots only','election'=>'All nominations and votes; keep members','all'=>'All members, nominations, and votes'][$r['scope']])?></strong>. Deleted records cannot be restored through the app.</div><form method="post" class="row g-3"><?=csrf()?><input type="hidden" name="action" value="confirm_reset"><div class="col-md-4"><label class="form-label" for="reset-code">Email verification code</label><input class="form-control" id="reset-code" name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" required></div><div class="col-md-4"><label class="form-label" for="reset-confirmation">Type RESET to confirm</label><input class="form-control" id="reset-confirmation" name="confirmation" required autocomplete="off"></div><div class="col-md-4 d-flex align-items-end"><button class="btn btn-danger" data-confirm="Permanently delete the selected election records?">Confirm permanent reset</button></div></form><div class="mt-3"><?php postButton('cancel_reset','Cancel reset',[],'btn-light');?></div><?php else:?><form method="post" class="row g-3"><?=csrf()?><input type="hidden" name="action" value="request_reset"><div class="col-md-5"><label class="form-label" for="scope">What should be reset?</label><select class="form-select" id="scope" name="scope"><option value="election">Nominations & votes — keep members</option><option value="votes" <?=!in_array($el['phase'],['voting','closed'],true)?'disabled':''?>>Voting only — keep nominees, return to review</option><option value="all">Everything — including member register</option></select></div><div class="col-md-4"><label class="form-label" for="reset-password">Your admin password</label><input class="form-control" type="password" id="reset-password" name="password" autocomplete="current-password" required></div><div class="col-md-3 d-flex align-items-end"><button class="btn btn-outline-danger">Send reset code</button></div></form><p class="small-note mt-3 mb-0">Admin accounts, election limits, and the activity log are retained. Every reset invalidates existing member verifications.</p><?php endif?></div></section>
<?php }
function auditPage(): void {
    pageTitle('ADMINISTRATOR HISTORY','Activity log','A record of administrative actions, phase changes, and verified resets.');
    $rows=query('SELECT l.*,a.name AS admin_name FROM audit_log l LEFT JOIN admins a ON a.id=l.admin_id ORDER BY l.id DESC LIMIT 200')->fetchAll(); ?>
<section class="panel"><?php if(!$rows): emptyState('No activity yet','Administrative actions will appear here.','clock'); else:?><div class="table-responsive"><table class="table app-table"><thead><tr><th>Time (UTC)</th><th>Administrator</th><th>Action</th><th>Details</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['created_at'])?></td><td><?=e($r['admin_name']??'System')?></td><td><?=e(ucwords(str_replace('_',' ',$r['action'])))?></td><td class="audit-details"><?=e($r['details'])?></td></tr><?php endforeach?></tbody></table></div><div class="table-footer">Showing the 200 most recent actions.</div><?php endif?></section>
<?php }
function authStart(string $title,string $caption): void { head($title); ?><div class="auth-layout"><aside class="auth-aside"><a class="brand" href="index.php"><span class="brand-mark"><?=icon('ballot')?></span>assembly<span class="brand-period">.</span></a><div class="auth-story"><div class="eyebrow">YOUR COMMUNITY. YOUR CHOICE.</div><h1>A stronger community<br>starts with your voice.</h1><p>A simple, trusted way to nominate your leaders and elect your officers.</p><div class="auth-art"><?=icon('ballot')?><div class="auth-art-line"></div><?=icon('users')?></div></div><div class="auth-aside-footer"><?=icon('shield')?> Verified members. Meaningful choices.</div></aside><main class="auth-main"><a class="mobile-brand" href="index.php">assembly.</a><div class="auth-card"><div class="eyebrow">ASSEMBLY ELECTIONS</div><h1><?=e($title)?></h1><p class="body-muted mb-4"><?=e($caption)?></p><?php notices(); }
function authEnd(): void { ?></div><footer class="auth-footer"><?=icon('shield')?> Your participation is protected by email verification.</footer></main></div><?php foot(); }
function renderLogin(): void { if(admin()) redirect('index.php'); authStart('Welcome back','Sign in to manage your community’s election.'); ?>
<form method="post"><?=csrf()?><input type="hidden" name="action" value="login"><label class="form-label" for="email">Admin email</label><input class="form-control mb-3" type="email" name="email" id="email" autocomplete="username" required><label class="form-label" for="password">Password</label><input class="form-control mb-4" type="password" name="password" id="password" autocomplete="current-password" required><button class="btn btn-primary w-100">Sign in <?=icon('arrow')?></button></form><div class="auth-divider"></div><p class="text-secondary text-center">Here to participate?</p><div class="d-flex gap-3 justify-content-center"><a class="text-link" href="index.php?page=participate&stage=nomination">Nominate members</a><a class="text-link" href="index.php?page=participate&stage=voting">Cast your vote</a></div>
<?php authEnd(); }
function renderMember(string $stage): void {
    if(!in_array($stage,['nomination','voting'],true)) { http_response_code(404); authStart('Page not found','Use the QR code provided by your administrator.'); authEnd(); return; }
    $el=election();
    if($el['phase']!==$stage) { authStart($stage==='nomination'?'Nominations are not open':'Voting is not open','Please wait for your administrator to open this stage.'); ?><div class="member-state"><?=icon('clock')?><h2><?=e($el['title'])?></h2><p>Current stage: <?=e(ucfirst($el['phase']))?></p><a class="btn btn-outline-primary" href="index.php?page=participate&stage=<?=e($stage)?>">Check again</a></div><?php authEnd(); return; }
    $v=$_SESSION['verified']??null;
    if($v && ($v['stage']!==$stage || $v['generation']!==(int)$el['generation'] || $v['expires']<time())) { unset($_SESSION['verified']); $v=null; }
    if($v) {
        $m=one('SELECT * FROM members WHERE id=? AND active=1',[$v['member_id']]);
        if(!$m) { unset($_SESSION['verified']); redirect('index.php?page=participate&stage='.$stage); }
        $done=one('SELECT * FROM submissions WHERE member_id=? AND stage=?',[$m['id'],$stage]);
        if($done) { authStart($stage==='nomination'?'Nominations submitted':'Your vote is recorded','Thank you, '.$m['first_name'].'. Your voice is part of this election.'); ?><div class="member-state success-state"><?=icon('check')?><h2>All done!</h2><p>You have completed your submission for this stage. Each member can submit only once.</p><p class="small-note">Submitted <?=e($done['created_at'])?> UTC</p></div><?php postButton('start_over','Finish and sign out',[],'btn-outline-primary w-100'); authEnd(); return; }
        $limit=(int)$el[$stage==='nomination'?'nomination_limit':'vote_limit']; $rows=$stage==='nomination'?query('SELECT * FROM members WHERE active=1 ORDER BY last_name,first_name,id')->fetchAll():tally('voting');
        head($stage==='nomination'?'Nominate members':'Vote for officers'); ?>
<div class="member-shell"><header class="member-header"><a class="brand brand-dark" href="index.php?page=participate&stage=<?=e($stage)?>"><span class="brand-mark"><?=icon('ballot')?></span>assembly.</a><span class="verified-label"><?=icon('shield')?> Verified member</span></header><main class="ballot-main"><?php notices();?><div class="eyebrow"><?=e($el['title'])?></div><h1><?=$stage==='nomination'?'Who would you like to nominate?':'Choose your next leaders.'?></h1><p class="body-muted">Hello, <?=e($m['first_name'])?>. Select between 1 and <?=e($limit)?> <?=$stage==='nomination'?'members to nominate':'accepted candidates'?>. Your submission is final.</p>
<form method="post" id="ballot-form" data-limit="<?=$limit?>"><?=csrf()?><input type="hidden" name="action" value="submit_ballot"><section class="panel"><div class="panel-heading"><h2><?=$stage==='nomination'?'Member list':'Accepted nominees'?> <span class="count-pill"><?=count($rows)?></span></h2><div class="search-field"><?=icon('search')?><label class="visually-hidden" for="ballot-search">Search names</label><input id="ballot-search" placeholder="Search members" type="search"></div></div><div class="table-responsive"><table class="table app-table ballot-table"><thead><tr><th>Select</th><th><?=$stage==='nomination'?'Member name':'Candidate name'?></th></tr></thead><tbody><?php foreach($rows as $r):?><tr data-search="<?=e(mb_strtolower(name($r)))?>"><td><input class="form-check-input candidate-check" type="checkbox" name="candidates[]" id="candidate-<?=e($r['id'])?>" value="<?=e($r['id'])?>"></td><td><label for="candidate-<?=e($r['id'])?>"><?=e(name($r))?></label></td></tr><?php endforeach?></tbody></table></div><p class="p-4 text-secondary d-none" id="no-search-results">No names match your search.</p></section><div class="ballot-submit"><div><strong id="selection-count" aria-live="polite">0 of <?=$limit?> selected</strong><p>You may select fewer than <?=$limit?>.</p></div><button class="btn btn-primary" data-confirm="Submit these selections? You cannot change them after submission.">Submit <?=$stage==='nomination'?'nominations':'vote'?> <?=icon('arrow')?></button></div><div id="ballot-error" class="alert alert-warning d-none" role="alert"></div></form><div class="text-center mt-4"><?php postButton('start_over','Sign out',[],'btn-link');?></div></main></div>
<?php foot(); return;
    }
    $c=$_SESSION['challenge']??null;
    if($c && ($c['stage']!==$stage || $c['generation']!==(int)$el['generation'])) { unset($_SESSION['challenge']); $c=null; }
    authStart($c?'Check your email':'Verify your membership',$c?'Enter the six-digit code sent to your registered email.':'Use the email address registered with your organization.'); ?>
<div class="stage-caption"><?=icon('ballot')?> <?=e($el['title'])?> · <?=$stage==='nomination'?'Nominations':'Voting'?></div>
<?php if($c):?><p class="small-note">Code requested for <strong><?=e($c['email'])?></strong>. If it is not in your inbox or spam folder, check with the administrator that your email is registered.</p><form method="post"><?=csrf()?><input type="hidden" name="action" value="verify_otp"><label class="form-label" for="code">Verification code</label><input class="form-control otp-input mb-3" id="code" name="code" pattern="[0-9]{6}" inputmode="numeric" maxlength="6" autocomplete="one-time-code" placeholder="000000" required autofocus><p class="small-note">Expires in 10 minutes · Maximum 5 attempts</p><button class="btn btn-primary w-100">Verify and continue <?=icon('arrow')?></button></form><form method="post" class="mt-3 text-center"><?=csrf()?><input type="hidden" name="action" value="request_otp"><input type="hidden" name="email" value="<?=e($c['email'])?>"><button class="btn btn-link">Resend code (after 60 seconds)</button></form><?php postButton('start_over','Use another email',[],'btn-light w-100');?>
<?php else:?><form method="post"><?=csrf()?><input type="hidden" name="action" value="request_otp"><label for="email" class="form-label">Registered email address</label><input class="form-control mb-4" id="email" type="email" name="email" autocomplete="email" maxlength="254" placeholder="you@example.com" required><button class="btn btn-primary w-100">Send verification code <?=icon('arrow')?></button></form><p class="small-note mt-4">Only members added by your administrator can participate. Contact your administrator if you need help with your registration.</p><?php endif; authEnd();
}
